Project Title

In [1]:
# SpendDNA - Week 2 Minor Project
# The Unlox Academy
# Student: Sumukh R
# Domain: Data Analytics
# Dataset: rahul_transactions.csv

print("=" * 70)
print(" " * 20 + "SpendDNA")
print(" " * 12 + "Your Wallet's Financial DNA")
print("=" * 70)
print("Student : Sumukh R")
print("Project : Unlox Academy - Week 2 Minor Project")
print("Dataset : Rahul Transactions")
print("=" * 70)

======================================================================
                    SpendDNA
            Your Wallet's Financial DNA
======================================================================
Student : Sumukh R
Project : Unlox Academy - Week 2 Minor Project
Dataset : Rahul Transactions
======================================================================

Import Libraries

In [2]:
import pandas as pd
import numpy as np
from datetime import datetime

print("Libraries imported successfully.")

Libraries imported successfully.

Upload CSV

In [3]:
from google.colab import files

uploaded = files.upload()

print("File uploaded successfully.")

Saving rahul_transactions.csv to rahul_transactions (1).csv
File uploaded successfully.

Read Dataset

In [4]:
df = pd.read_csv("rahul_transactions.csv")

print("Dataset loaded successfully.")
print("Shape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nFirst 5 rows:")
display(df.head())

Dataset loaded successfully.
Shape: (1328, 8)

Columns:
['Date', 'Time', 'Description', 'Type', 'Amount', 'Balance', 'Mode', 'Ref']

First 5 rows:

,Date,Time,Description,Type,Amount,Balance,Mode,Ref
0,2024-01-01,03:11,AMAZON SELLER SVCS,Debit,₹2462,678275.0,UPI,TXN190872
1,01-Jan-24,05:44,BHIM-BMTC,DR,50.00,681007.0,UPI,TXN143064
2,01-Jan-24,09:35,NEFT-TECHCRUSH LABS-SALARY MAY24,CR,₹84728,484728.0,NEFT,TXN246316
3,2024-01-01,14:07,UPI-AMAN-8934@OKAXIS,Debit,₹1828,-748745.0,UPI,TXN569226
4,01 Jan 2024,14:23,BHIM-BLINKIT,Debit,270.00,680737.0,UPI,TXN968962

Initial Dataset Inspection

In [5]:
print("=" * 70)
print("INITIAL DATASET INSPECTION")
print("=" * 70)

print("\nNumber of rows:", len(df))
print("Number of columns:", len(df.columns))

print("\nData types:")
print(df.dtypes)

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate rows:")
print(df.duplicated().sum())

print("\nTransaction types:")
print(df["Type"].value_counts(dropna=False))

======================================================================
INITIAL DATASET INSPECTION
======================================================================

Number of rows: 1328
Number of columns: 8

Data types:
Date            object
Time            object
Description     object
Type            object
Amount          object
Balance        float64
Mode            object
Ref             object
dtype: object

Missing values:
Date           0
Time           0
Description    0
Type           0
Amount         0
Balance        0
Mode           0
Ref            0
dtype: int64

Duplicate rows:
18

Transaction types:
Type
DR       670
Debit    652
CR         6
Name: count, dtype: int64

Inspect Raw Descriptions

In [6]:
print("=" * 70)
print("UNIQUE TRANSACTION DESCRIPTIONS")
print("=" * 70)

unique_descriptions = df["Description"].dropna().unique()

print("Number of unique descriptions:", len(unique_descriptions))

for description in unique_descriptions:
    print(description)

======================================================================
UNIQUE TRANSACTION DESCRIPTIONS
======================================================================
Number of unique descriptions: 283
AMAZON SELLER SVCS
BHIM-BMTC
NEFT-TECHCRUSH LABS-SALARY MAY24
UPI-AMAN-8934@OKAXIS
BHIM-BLINKIT
BHIM ZEPTO
UPI-UBER-2426@HDFCBANK
POS SWIGGY BANGALORE
UPI-GROWWPAY@HDFCBANK
OLA ELECTRIC
BMS MOVIE TICKETS
POS OLA-PRIME
SWIGGY-INSTAMART
UPI-STARBUCKS@AXIS
UPI-THIRDWAVE@OKAXIS
ANI Technologies
BMTC BUS PASS
POS TRUFFLES
FLIPKART INDIA
POS SWIGGY-RESTAURANT
GROFERS INDIA P L
POS UBER BANGALORE
BANGALORE ELEC SUPPLY
TWC INDIA
UPI-BESCOM-BILL@HDFCBANK
UPI-AMAN-0816@OKAXIS
ROPPEN TRANSPORTATION
OLA CABS
POS ZOMATO
UPI-AMAZONPAY@HDFCBANK
POS BLINKIT
IMPS-RENT-LANDLORD-75500265
ZOMATO MEDIA P L
UPI-ANKIT-6430@OKAXIS
UPI-OLACABS@HDFCBANK
UPI-JIORECHARGE@PAYTM
UPI-CCD@HDFCBANK
Swiggy*Order
INSTAMART BANGALORE
UPI-ZOMATO-LIMITED@PAYTM
AVENUE SUPERMARTS
POS HP PETROL STATION
UPI-VIKAS-6060@OKAXIS
POS BANGALORE RESTAURANT
UPI-ZERODHA-COIN@AXIS
BHIM SWIGGY
UPI-BOOKMYSHOW@HDFCBANK
BLINKIT BANGALORE
POS ZEPTO BANGALORE
UPI-DMART@OKAXIS
UPI-RAPIDO@OKAXIS
BUNDL Tech P L
TATA STARBUCKS
POS CAFE COFFEE DAY
UBER SYSTEMS INDIA
UPI-MYNTRA@HDFCBANK
UPI-FLIPKART@HDFCBANK
UPI-BWSSB@AXIS
UPI-ZOMATO6393@OKICICI
AMAZON IN
UPI-NETFLIX-MEMB@HDFCBANK
AIRTEL POSTPAID
Amazon Pay India
UPI-PRIYA-2221@OKAXIS
POS FLIPKART BANGALORE
POS NYKAA BANGALORE
VI POSTPAID
UPI-UBER-6457@HDFCBANK
POS BPCL PETROL PUMP
TUMMOC-BMTC
POS INDIAN OIL BANGALORE
UPI-SPOTIFY-IN@AXIS
POS DINEOUT
UPI-BLINKIT-0656@PAYTM
UPI-SWIGGY5057@OKAXIS
ZOMATO-DINING
COFFEE DAY GLOBAL
UPI-NYKAA@AXIS
UPI-SWIGGY9672@OKAXIS
RAPIDO BIKE TAXI
UPI-SWIGGY-6560@HDFCBANK
DISNEY HOTSTAR
NEFT ZERODHA BROKING
UBER INDIA
AMAZONIN MARKETPLACE
UPI-ZOMATO4674@OKICICI
POS EMPIRE RESTAURANT
ATM-WDL-SBI-5715
UPI-SWIGGY-9474@HDFCBANK
POS MEGHANA FOODS
ZEPTO MARKETPLACE
UPI-IOC9075@HDFCBANK
UPI-SWIGGY-2954@HDFCBANK
FKART INTRNET
UPI-SWIGGY-5808@HDFCBANK
UPI-BIGBASKET@HDFCBANK
AMZN-INTPYMT
AMZN PRIME
MYNTRA-ORDER
UPI-SWIGGY-5551@HDFCBANK
BUNDL TECH-INSTAMART
MYNTRA DESIGNS
POS MYNTRA
POS DMART BANGALORE
BIGBASKET BANGALORE
POS THIRD WAVE COFFEE
SPOTIFY INDIA
UPI-SWIGGY-7959@HDFCBANK
UPI-BLINKIT-3798@PAYTM
UPI-BLINKIT-3397@PAYTM
UPI-SWIGGY-INSTAMART@OKAXIS
ZOMATO BENGALURU
BESCOM ELEC BILL
IMPS-RENT-LANDLORD-39598076
UPI-RESTAURANT-7285@PAYTM
POS STARBUCKS BANGALORE
UPI-SWIGGY2461@OKAXIS
UPI-SWIGGY4619@OKAXIS
IMPS ZERODHA-COIN
UPI-SWIGGY3675@OKAXIS
RELIANCE JIO
UPI-SWIGGY-1309@HDFCBANK
NETFLIX ENTERTAINMENT
UPI-UBER-5667@HDFCBANK
FSN E-COMMERCE
UPI-BLINKIT-2630@PAYTM
UPI-RESTAURANT-7678@PAYTM
ATM-WDL-HDFC-4942
Uber*Trip
UPI-SWIGGY1616@OKAXIS
UPI-NEHA-9795@OKAXIS
BIGTREE ENTERTAINMENT
UPI-ZOMATO4177@OKICICI
INNOVATIVE RETAIL
POS INSTAMART
UPI-RESTAURANT-3715@PAYTM
UPI-UBER-1232@HDFCBANK
STAR INDIA PVT LTD
UPI-SWIGGY-5933@HDFCBANK
UPI-RESTAURANT-0251@PAYTM
UPI-ZOMATO3977@OKICICI
UPI-BLINKIT-7138@PAYTM
UPI-SWIGGY8086@OKAXIS
UPI-SWIGGY-6605@HDFCBANK
AMAZON PRIME VIDEO
UPI-SWIGGY-7844@HDFCBANK
UPI-SWIGGY-1487@HDFCBANK
UPI-UBER-6248@HDFCBANK
UPI-NEHA-5906@OKAXIS
KIRANAKART TECH
UPI-SWIGGY-7642@HDFCBANK
UPI-ZEPTO-4547@HDFCBANK
UPI-ZEPTO-4563@HDFCBANK
IMPS-RENT-LANDLORD-51148088
UPI-RESTAURANT-6377@PAYTM
UPI-ZEPTO-3309@HDFCBANK
UPI-ZEPTO-0070@HDFCBANK
UPI-SWIGGY-8169@HDFCBANK
UPI-VIKAS-5416@OKAXIS
UPI-HOTSTAR@AXIS
ATM-WDL-HDFC-9140
UPI-ZOMATO6436@OKICICI
ATM-WDL-SBI-4080
NETFLIX.COM
UPI-IOC0494@HDFCBANK
UPI-RESTAURANT-4630@PAYTM
UPI-IOC1246@HDFCBANK
Flipkart Internet
UPI-SWIGGY1600@OKAXIS
UPI-SWIGGY8576@OKAXIS
ATM-WDL-HDFC-8030
SPOTIFY*PREMIUM
UPI-BLINKIT-6907@PAYTM
BWSSB WATER BILL
UPI-RESTAURANT-7888@PAYTM
GROWW INVEST TECH
UPI-IOC2000@HDFCBANK
UPI-SWIGGY5466@OKAXIS
UPI-SNEHA-0942@OKAXIS
UPI-SWIGGY-2664@HDFCBANK
JIOFIBER
BHARTI AIRTEL LTD
UPI-UBER-0377@HDFCBANK
UPI-UBER-5112@HDFCBANK
UPI-ZOMATO1274@OKICICI
UPI-SWIGGY4144@OKAXIS
UPI-VI-RECHARGE@HDFCBANK
UPI-KARAN-5789@OKAXIS
UPI-BLINKIT-1501@PAYTM
ZERODHA-MF SIP
UPI-SWIGGY-9575@HDFCBANK
UPI-RESTAURANT-0753@PAYTM
NEXTBILLION-GROWW
UPI-ZOMATO5010@OKICICI
UPI-BLINKIT-1469@PAYTM
UPI-SWIGGY9328@OKAXIS
NYKAA E-RETAIL
ATM-WDL-HDFC-3609
UPI-SWIGGY0226@OKAXIS
UPI-SWIGGY9600@OKAXIS
IMPS-RENT-LANDLORD-36852906
UPI-ZOMATO7344@OKICICI
UPI-ZEPTO-9191@HDFCBANK
UPI-ZOMATO9481@OKICICI
UPI-IOC2115@HDFCBANK
UPI-SWIGGY-3513@HDFCBANK
UPI-RESTAURANT-3549@PAYTM
UPI-PRIYA-8750@OKAXIS
UPI-ZOMATO5845@OKICICI
UPI-ZEPTO-6004@HDFCBANK
UPI-BLINKIT-3223@PAYTM
UPI-SWIGGY1998@OKAXIS
ATM-WDL-ICICI-6478
UPI-SWIGGY0250@OKAXIS
UPI-RESTAURANT-5630@PAYTM
UPI-SWIGGY0894@OKAXIS
UPI-ANKIT-9877@OKAXIS
UPI-SWIGGY6412@OKAXIS
UPI-SWIGGY-1791@HDFCBANK
UPI-SWIGGY5867@OKAXIS
UPI-UBER-8525@HDFCBANK
UPI-SWIGGY-4758@HDFCBANK
UPI-BLINKIT-1165@PAYTM
UPI-SWIGGY4389@OKAXIS
ATM-WDL-SBI-0237
IMPS-RENT-LANDLORD-49966195
UPI-SWIGGY8720@OKAXIS
UPI-PRIYA-0104@OKAXIS
UPI-RESTAURANT-8932@PAYTM
UPI-SWIGGY9756@OKAXIS
UPI-SWIGGY-1714@HDFCBANK
VODAFONE IDEA LTD
ATM-WDL-SBI-0279
UPI-SWIGGY-6024@HDFCBANK
UPI-ZEPTO-2913@HDFCBANK
UPI-ZOMATO5406@OKICICI
UPI-RESTAURANT-3964@PAYTM
UPI-SWIGGY5737@OKAXIS
ATM-WDL-HDFC-8253
ZERODHA SECURITIES
UPI-AMAZON-PRIME@HDFCBANK
UPI-UBER-4781@HDFCBANK
UPI-RESTAURANT-5691@PAYTM
UPI-SWIGGY2847@OKAXIS
UPI-ZOMATO9682@OKICICI
UPI-IOC5182@HDFCBANK
UPI-ANKIT-5946@OKAXIS
UPI-SWIGGY9088@OKAXIS
UPI-UBER-1392@HDFCBANK
UPI-SWIGGY9983@OKAXIS
UPI-ZEPTO-1050@HDFCBANK
UPI-ANKIT-1837@OKAXIS
IMPS-RENT-LANDLORD-35126704
UPI-SWIGGY8392@OKAXIS
UPI-ZOMATO5117@OKICICI
UPI-ZOMATO4622@OKICICI
UPI-SWIGGY1418@OKAXIS
ATM-WDL-ICICI-9135
UPI-RESTAURANT-5531@PAYTM
UPI-ANKIT-6092@OKAXIS
UPI-SWIGGY7538@OKAXIS
ATM-WDL-ICICI-4172
UPI-ZEPTO-5207@HDFCBANK
ATM-WDL-SBI-4084
UPI-ZEPTO-7106@HDFCBANK
ATM-WDL-ICICI-4739
UPI-SWIGGY6053@OKAXIS
UPI-SWIGGY-3505@HDFCBANK
UPI-SWIGGY-0015@HDFCBANK
UPI-RESTAURANT-2648@PAYTM
ATM-WDL-SBI-0874
UPI-VIKAS-1878@OKAXIS
UPI-SWIGGY6013@OKAXIS
UPI-SWIGGY-8838@HDFCBANK
UPI-VIKAS-9964@OKAXIS
UPI-RESTAURANT-7645@PAYTM
ATM-WDL-ICICI-3918
UPI-SWIGGY-9077@HDFCBANK
UPI-RESTAURANT-0874@PAYTM
ATM-WDL-ICICI-5025
UPI-SWIGGY3466@OKAXIS
UPI-BLINKIT-1828@PAYTM
UPI-UBER-3218@HDFCBANK

FEATURE 1: Transaction Parser

In [7]:
# AI-assisted: Syntax assistance for cleaning mixed date and amount formats.

df_clean = df.copy()

# -----------------------------
# DATE CLEANING
# -----------------------------
df_clean["date"] = pd.to_datetime(
    df_clean["Date"],
    errors="coerce",
    dayfirst=True
)

# -----------------------------
# AMOUNT CLEANING
# -----------------------------
df_clean["amount"] = (
    df_clean["Amount"]
    .astype(str)
    .str.replace("₹", "", regex=False)
    .str.replace("Rs.", "", regex=False)
    .str.replace(",", "", regex=False)
    .str.strip()
)

df_clean["amount"] = pd.to_numeric(
    df_clean["amount"],
    errors="coerce"
)

# -----------------------------
# TYPE STANDARDIZATION
# -----------------------------
df_clean["type"] = (
    df_clean["Type"]
    .astype(str)
    .str.strip()
    .str.lower()
)

df_clean["type"] = df_clean["type"].replace({
    "dr": "debit",
    "debit": "debit",
    "cr": "credit",
    "credit": "credit"
})

# -----------------------------
# MODE CLEANING
# -----------------------------
df_clean["Mode"] = (
    df_clean["Mode"]
    .replace("", np.nan)
)

# -----------------------------
# DUPLICATES
# -----------------------------
duplicates_before = df_clean.duplicated().sum()

df_clean = df_clean.drop_duplicates().copy()

# -----------------------------
# INVALID DATA CHECK
# -----------------------------
invalid_dates = df_clean["date"].isna().sum()
invalid_amounts = df_clean["amount"].isna().sum()

print("=" * 70)
print("FEATURE 1 - TRANSACTION PARSER")
print("=" * 70)

print("Original transactions :", len(df))
print("Duplicate rows removed:", duplicates_before)
print("Clean transactions    :", len(df_clean))
print("Unparseable dates     :", invalid_dates)
print("Unparseable amounts   :", invalid_amounts)

print("\nCleaned data types:")
print(df_clean[["date", "amount", "type"]].dtypes)

======================================================================
FEATURE 1 - TRANSACTION PARSER
======================================================================
Original transactions : 1328
Duplicate rows removed: 18
Clean transactions    : 1310
Unparseable dates     : 1167
Unparseable amounts   : 0

Cleaned data types:
date      datetime64[ns]
amount           float64
type              object
dtype: object

Verify Parser

In [8]:
print("=" * 70)
print("PARSER VERIFICATION")
print("=" * 70)

print("\nDate range:")
print(df_clean["date"].min(), "to", df_clean["date"].max())

print("\nTransaction types:")
print(df_clean["type"].value_counts())

print("\nAmount summary:")
print(df_clean["amount"].describe())

print("\nCleaned sample:")
display(
    df_clean[
        ["Date", "date", "Description", "Amount", "amount", "Type", "type"]
    ].head(10)
)

======================================================================
PARSER VERIFICATION
======================================================================

Date range:
2024-01-01 00:00:00 to 2024-12-06 00:00:00

Transaction types:
type
debit     1304
credit       6
Name: count, dtype: int64

Amount summary:
count     1310.000000
mean      1670.744275
std       6306.346647
min         10.000000
25%        295.250000
50%        477.000000
75%       1009.750000
max      85492.000000
Name: amount, dtype: float64

Cleaned sample:

,Date,date,Description,Amount,amount,Type,type
0,2024-01-01,2024-01-01,AMAZON SELLER SVCS,₹2462,2462.0,Debit,debit
1,01-Jan-24,NaT,BHIM-BMTC,50.00,50.0,DR,debit
2,01-Jan-24,NaT,NEFT-TECHCRUSH LABS-SALARY MAY24,₹84728,84728.0,CR,credit
3,2024-01-01,2024-01-01,UPI-AMAN-8934@OKAXIS,₹1828,1828.0,Debit,debit
4,01 Jan 2024,NaT,BHIM-BLINKIT,270.00,270.0,Debit,debit
5,2024-01-01,2024-01-01,BHIM ZEPTO,Rs. 625,625.0,DR,debit
6,2024-01-01,2024-01-01,UPI-UBER-2426@HDFCBANK,Rs. 148,148.0,Debit,debit
7,01-Jan-24,NaT,BHIM-BLINKIT,₹482,482.0,Debit,debit
8,2024-01-02,2024-02-01,POS SWIGGY BANGALORE,Rs. 537,537.0,Debit,debit
9,02/01/24,NaT,UPI-GROWWPAY@HDFCBANK,3956,3956.0,DR,debit

FEATURE 2: Vendor Dictionary

In [9]:
# AI-assisted: Initial vendor keyword dictionary structure.
# Vendor patterns were aligned to the actual descriptions in rahul_transactions.csv.

vendor_keywords = {

    "Swiggy": [
        "SWIGGY",
        "BUNDL"
    ],

    "Zomato": [
        "ZOMATO"
    ],

    "Zepto": [
        "ZEPTO"
    ],

    "Blinkit": [
        "BLINKIT",
        "GROFERS"
    ],

    "Instamart": [
        "INSTAMART"
    ],

    "BigBasket": [
        "BIGBASKET"
    ],

    "DMart": [
        "DMART",
        "AVENUE SUPERMARTS"
    ],

    "Amazon": [
        "AMAZON",
        "AMZN"
    ],

    "Flipkart": [
        "FLIPKART",
        "FKART"
    ],

    "Myntra": [
        "MYNTRA"
    ],

    "Nykaa": [
        "NYKAA",
        "FSN E-COMMERCE"
    ],

    "Uber": [
        "UBER",
        "ANI TECHNOLOGIES"
    ],

    "Ola": [
        "OLA"
    ],

    "Rapido": [
        "RAPIDO"
    ],

    "BMTC": [
        "BMTC",
        "TUMMOC"
    ],

    "Starbucks": [
        "STARBUCKS",
        "TATA STARBUCKS"
    ],

    "Third Wave Coffee": [
        "THIRDWAVE",
        "THIRD WAVE"
    ],

    "Cafe Coffee Day": [
        "CCD",
        "COFFEE DAY"
    ],

    "Truffles": [
        "TRUFFLES"
    ],

    "Empire Restaurant": [
        "EMPIRE"
    ],

    "Meghana Foods": [
        "MEGHANA"
    ],

    "Bangalore Restaurant": [
        "BANGALORE RESTAURANT",
        "UPI-RESTAURANT",
        "RESTAURANT"
    ],

    "BookMyShow": [
        "BOOKMYSHOW",
        "BMS MOVIE"
    ],

    "Netflix": [
        "NETFLIX"
    ],

    "Spotify": [
        "SPOTIFY"
    ],

    "Disney Hotstar": [
        "HOTSTAR",
        "DISNEY"
    ],

    "Airtel": [
        "AIRTEL",
        "BHARTI AIRTEL"
    ],

    "Vi": [
        "VODAFONE IDEA",
        "VI POSTPAID",
        "UPI-VI"
    ],

    "Jio": [
        "JIO",
        "RELIANCE JIO"
    ],

    "Bescom": [
        "BESCOM",
        "BANGALORE ELEC"
    ],

    "BWSSB": [
        "BWSSB"
    ],

    "Indian Oil": [
        "INDIAN OIL",
        "IOC"
    ],

    "HP Petrol": [
        "HP PETROL"
    ],

    "BPCL": [
        "BPCL"
    ],

    "Zerodha": [
        "ZERODHA"
    ],

    "Groww": [
        "GROWW",
        "NEXTBILLION"
    ]
}

print("Number of canonical vendors in dictionary:", len(vendor_keywords))

Number of canonical vendors in dictionary: 36

Vendor Extraction Function

In [10]:
def extract_vendor(description):

    description = str(description).upper()

    # Special case: ATM withdrawal
    if "ATM-WDL" in description:
        return "Cash Withdrawal"

    # Special case: rent
    if "RENT-LANDLORD" in description:
        return "Rent"

    # Special case: salary
    if "SALARY" in description:
        return "Salary"

    # Check canonical vendor keywords
    for vendor, keywords in vendor_keywords.items():

        for keyword in keywords:

            if keyword.upper() in description:
                return vendor

    # P2P transfers
    if "UPI-" in description and "@" in description:
        return "P2P Transfer"

    return "Uncategorised"


df_clean["vendor_clean"] = df_clean["Description"].apply(extract_vendor)

print("=" * 70)
print("FEATURE 2 - VENDOR EXTRACTOR")
print("=" * 70)

print("Unique vendors:", df_clean["vendor_clean"].nunique())

print("\nTop vendors:")
print(df_clean["vendor_clean"].value_counts().head(15))

======================================================================
FEATURE 2 - VENDOR EXTRACTOR
======================================================================
Unique vendors: 41

Top vendors:
vendor_clean
Swiggy                  223
Zomato                  121
Uber                     89
Amazon                   86
Ola                      69
Uncategorised            59
Zepto                    58
Blinkit                  55
Flipkart                 47
Starbucks                42
Rapido                   41
BMTC                     37
Bangalore Restaurant     29
Cafe Coffee Day          26
Third Wave Coffee        22
Name: count, dtype: int64

Vendor Audit

In [11]:
print("=" * 70)
print("VENDOR CLEANUP AUDIT")
print("=" * 70)

uncategorised = df_clean[
    df_clean["vendor_clean"] == "Uncategorised"
]

print("Uncategorised transactions:", len(uncategorised))

if len(uncategorised) > 0:

    print("\nDescriptions that need review:")

    for item in uncategorised["Description"].unique():
        print("-", item)

else:
    print("All descriptions successfully mapped.")

======================================================================
VENDOR CLEANUP AUDIT
======================================================================
Uncategorised transactions: 59

Descriptions that need review:
- TWC INDIA
- ROPPEN TRANSPORTATION
- POS DINEOUT
- BIGTREE ENTERTAINMENT
- INNOVATIVE RETAIL
- STAR INDIA PVT LTD
- KIRANAKART TECH

FEATURE 3: Category Tagger

In [12]:
category_mapping = {

    # Food
    "Swiggy": "Food Delivery",
    "Zomato": "Food Delivery",

    # Quick Commerce
    "Zepto": "Quick Commerce",
    "Blinkit": "Quick Commerce",
    "Instamart": "Quick Commerce",
    "BigBasket": "Quick Commerce",
    "DMart": "Groceries",

    # E-commerce
    "Amazon": "E-commerce",
    "Flipkart": "E-commerce",
    "Myntra": "E-commerce",
    "Nykaa": "E-commerce",

    # Transport
    "Uber": "Transport",
    "Ola": "Transport",
    "Rapido": "Transport",
    "BMTC": "Transport",

    # Cafe
    "Starbucks": "Cafe",
    "Third Wave Coffee": "Cafe",
    "Cafe Coffee Day": "Cafe",

    # Restaurants
    "Truffles": "Restaurants",
    "Empire Restaurant": "Restaurants",
    "Meghana Foods": "Restaurants",
    "Bangalore Restaurant": "Restaurants",

    # Entertainment
    "BookMyShow": "Entertainment",
    "Disney Hotstar": "Entertainment",

    # Subscriptions
    "Netflix": "Subscriptions",
    "Spotify": "Subscriptions",

    # Utilities
    "Airtel": "Utilities",
    "Vi": "Utilities",
    "Jio": "Utilities",
    "Bescom": "Utilities",
    "BWSSB": "Utilities",

    # Fuel
    "Indian Oil": "Fuel",
    "HP Petrol": "Fuel",
    "BPCL": "Fuel",

    # Investments
    "Zerodha": "Investments",
    "Groww": "Investments",

    # Special transactions
    "P2P Transfer": "Personal Transfer",
    "Cash Withdrawal": "Cash Withdrawal",
    "Rent": "Utilities",
    "Salary": "Income",

    "Uncategorised": "Uncategorised"
}

df_clean["category"] = (
    df_clean["vendor_clean"]
    .map(category_mapping)
    .fillna("Uncategorised")
)

print("=" * 70)
print("FEATURE 3 - CATEGORY TAGGER")
print("=" * 70)

print("\nCategory counts:")
print(df_clean["category"].value_counts())

======================================================================
FEATURE 3 - CATEGORY TAGGER
======================================================================

Category counts:
category
Food Delivery        344
Transport            236
E-commerce           172
Quick Commerce       144
Cafe                  90
Restaurants           63
Uncategorised         59
Utilities             53
Fuel                  28
Investments           23
Groceries             22
Entertainment         21
Subscriptions         18
Cash Withdrawal       17
Personal Transfer     14
Income                 6
Name: count, dtype: int64

Check All Categories

In [13]:
print("=" * 70)
print("CATEGORY VERIFICATION")
print("=" * 70)

categories = df_clean["category"].unique()

for category in sorted(categories):
    count = (df_clean["category"] == category).sum()
    print(f"{category:<22} : {count}")

======================================================================
CATEGORY VERIFICATION
======================================================================
Cafe                   : 90
Cash Withdrawal        : 17
E-commerce             : 172
Entertainment          : 21
Food Delivery          : 344
Fuel                   : 28
Groceries              : 22
Income                 : 6
Investments            : 23
Personal Transfer      : 14
Quick Commerce         : 144
Restaurants            : 63
Subscriptions          : 18
Transport              : 236
Uncategorised          : 59
Utilities              : 53

Create Date Features

In [14]:
# Date-related features

df_clean["month"] = df_clean["date"].dt.month

df_clean["month_name"] = df_clean["date"].dt.strftime("%b")

df_clean["day_of_week"] = df_clean["date"].dt.day_name()

df_clean["week_number"] = df_clean["date"].dt.isocalendar().week

# Time feature
df_clean["hour"] = (
    df_clean["Time"]
    .astype(str)
    .str[:2]
    .astype(int)
)

print("Date and time features created.")

Date and time features created.

Separate Credits and Debits

In [15]:
debits = df_clean[df_clean["type"] == "debit"].copy()

credits = df_clean[df_clean["type"] == "credit"].copy()

print("=" * 70)
print("TRANSACTION SPLIT")
print("=" * 70)

print("Total transactions :", len(df_clean))
print("Debit transactions :", len(debits))
print("Credit transactions:", len(credits))

======================================================================
TRANSACTION SPLIT
======================================================================
Total transactions : 1310
Debit transactions : 1304
Credit transactions: 6

FEATURE 4: Spending Overview

In [16]:
print("=" * 70)
print("FEATURE 4 - SPENDING OVERVIEW")
print("=" * 70)

total_credits = credits["amount"].sum()
total_debits = debits["amount"].sum()

net_change = total_credits - total_debits

if total_credits != 0:
    savings_rate = (net_change / total_credits) * 100
else:
    savings_rate = 0

transaction_count = len(df_clean)

unique_vendors = df_clean["vendor_clean"].nunique()

print(f"Total Credits       : ₹{total_credits:,.2f}")
print(f"Total Debits        : ₹{total_debits:,.2f}")
print(f"Net Change          : ₹{net_change:,.2f}")
print(f"Savings Rate        : {savings_rate:.2f}%")
print(f"Transactions        : {transaction_count}")
print(f"Unique Vendors      : {unique_vendors}")

======================================================================
FEATURE 4 - SPENDING OVERVIEW
======================================================================
Total Credits       : ₹509,774.00
Total Debits        : ₹1,678,901.00
Net Change          : ₹-1,169,127.00
Savings Rate        : -229.34%
Transactions        : 1310
Unique Vendors      : 41

Top Categories

In [17]:
consumption_categories = [
    "Food Delivery",
    "Quick Commerce",
    "E-commerce",
    "Transport",
    "Cafe",
    "Restaurants",
    "Subscriptions",
    "Utilities",
    "Groceries",
    "Investments",
    "Fuel",
    "Entertainment"
]

category_spend = (
    debits[
        debits["category"].isin(consumption_categories)
    ]
    .groupby("category")["amount"]
    .sum()
    .sort_values(ascending=False)
)

print("=" * 70)
print("TOP CATEGORIES")
print("=" * 70)

for category, amount in category_spend.items():

    percentage = (
        amount / category_spend.sum()
    ) * 100

    bar_length = int(percentage / 2)

    print(
        f"{category:<20} "
        f"{'#' * bar_length:<25} "
        f"{percentage:>6.2f}%  ₹{amount:,.2f}"
    )

======================================================================
TOP CATEGORIES
======================================================================
E-commerce           ###################        38.45%  ₹603,877.00
Investments          #######                    15.80%  ₹248,160.00
Utilities            ####                        9.85%  ₹154,674.00
Food Delivery        ####                        9.61%  ₹150,839.00
Restaurants          ###                         6.23%  ₹97,912.00
Fuel                 ##                          5.69%  ₹89,303.00
Quick Commerce       ##                          5.20%  ₹81,725.00
Transport            #                           3.56%  ₹55,884.00
Groceries            #                           2.39%  ₹37,463.00
Cafe                                             1.79%  ₹28,155.00
Entertainment                                    1.08%  ₹16,888.00
Subscriptions                                    0.35%  ₹5,504.00

Top Vendors

In [18]:
vendor_spend = (
    debits
    .groupby("vendor_clean")["amount"]
    .sum()
    .sort_values(ascending=False)
)

vendor_transactions = (
    debits
    .groupby("vendor_clean")
    .size()
    .sort_values(ascending=False)
)

print("=" * 70)
print("TOP 10 VENDORS")
print("=" * 70)

for vendor, amount in vendor_spend.head(10).items():

    count = vendor_transactions[vendor]

    print(
        f"{vendor:<22} ₹{amount:>12,.2f} "
        f"({count:>4} transactions)"
    )

======================================================================
TOP 10 VENDORS
======================================================================
Amazon                 ₹  328,530.00 (  86 transactions)
Zerodha                ₹  210,000.00 (  14 transactions)
Flipkart               ₹  177,510.00 (  47 transactions)
Rent                   ₹  108,000.00 (   6 transactions)
Swiggy                 ₹   95,523.00 ( 223 transactions)
Myntra                 ₹   69,529.00 (  20 transactions)
Indian Oil             ₹   56,335.00 (  17 transactions)
Zomato                 ₹   55,316.00 ( 121 transactions)
Cash Withdrawal        ₹   45,500.00 (  17 transactions)
Bangalore Restaurant   ₹   44,978.00 (  29 transactions)

FEATURE 5: Monthly Trend

In [19]:
month_order = [1, 2, 3, 4, 5, 6]

month_names = {
    1: "Jan",
    2: "Feb",
    3: "Mar",
    4: "Apr",
    5: "May",
    6: "Jun"
}

monthly_category = (
    debits[
        debits["category"].isin(consumption_categories)
    ]
    .pivot_table(
        values="amount",
        index="category",
        columns="month",
        aggfunc="sum",
        fill_value=0
    )
)

monthly_category = monthly_category.reindex(
    columns=month_order,
    fill_value=0
)

monthly_category.columns = [
    month_names[m] for m in monthly_category.columns
]

print("=" * 70)
print("FEATURE 5 - MONTHLY CATEGORY TREND")
print("=" * 70)

display(monthly_category.round(2))

======================================================================
FEATURE 5 - MONTHLY CATEGORY TREND
======================================================================

                   Jan     Feb      Mar     Apr      May     Jun
category
Cafe             295.0   355.0      0.0   688.0    166.0     0.0
E-commerce      6972.0   996.0   2147.0  3311.0      0.0  4868.0
Entertainment      0.0     0.0      0.0   343.0      0.0     0.0
Food Delivery   1180.0  3454.0   2862.0   632.0   1159.0  1636.0
Fuel               0.0     0.0      0.0     0.0      0.0     0.0
Groceries          0.0     0.0   1213.0     0.0      0.0     0.0
Investments        0.0     0.0      0.0     0.0      0.0     0.0
Quick Commerce  1616.0   697.0      0.0     0.0    502.0     0.0
Restaurants     1794.0     0.0   1748.0     0.0    753.0     0.0
Subscriptions      0.0     0.0      0.0     0.0      0.0     0.0
Transport       1287.0   888.0    439.0     0.0    431.0   134.0
Utilities          0.0     0.0  18000.0     0.0  18000.0  1860.0

Find Biggest Growth and Decline

In [20]:
print("=" * 70)
print("MONTHLY TREND SIGNALS")
print("=" * 70)

trend_results = []

for category in monthly_category.index:

    first_month = monthly_category.loc[category, "Jan"]
    last_month = monthly_category.loc[category, "Jun"]

    if first_month != 0:
        growth = (
            (last_month - first_month)
            / first_month
        ) * 100
    else:
        growth = np.nan

    trend_results.append(
        [category, first_month, last_month, growth]
    )

trend_df = pd.DataFrame(
    trend_results,
    columns=[
        "Category",
        "January Spend",
        "June Spend",
        "Growth %"
    ]
)

print("\nTrend comparison:")
display(trend_df.sort_values("Growth %", ascending=False).round(2))

valid_trends = trend_df.dropna(subset=["Growth %"])

if len(valid_trends) > 0:

    biggest_growth = valid_trends.loc[
        valid_trends["Growth %"].idxmax()
    ]

    biggest_decline = valid_trends.loc[
        valid_trends["Growth %"].idxmin()
    ]

    print(
        f"\nBiggest growth : {biggest_growth['Category']} "
        f"({biggest_growth['Growth %']:.2f}%)"
    )

    print(
        f"Biggest decline: {biggest_decline['Category']} "
        f"({biggest_decline['Growth %']:.2f}%)"
    )

======================================================================
MONTHLY TREND SIGNALS
======================================================================

Trend comparison:

          Category  January Spend  June Spend  Growth %
3    Food Delivery         1180.0      1636.0     38.64
1       E-commerce         6972.0      4868.0    -30.18
10       Transport         1287.0       134.0    -89.59
0             Cafe          295.0         0.0   -100.00
7   Quick Commerce         1616.0         0.0   -100.00
8      Restaurants         1794.0         0.0   -100.00
2    Entertainment            0.0         0.0       NaN
4             Fuel            0.0         0.0       NaN
5        Groceries            0.0         0.0       NaN
6      Investments            0.0         0.0       NaN
9    Subscriptions            0.0         0.0       NaN
11       Utilities            0.0      1860.0       NaN

Biggest growth : Food Delivery (38.64%)
Biggest decline: Cafe (-100.00%)

FEATURE 6: Time-of-Day Matrix

In [21]:
hour_category = (
    debits[
        debits["category"].isin(consumption_categories)
    ]
    .pivot_table(
        values="amount",
        index="category",
        columns="hour",
        aggfunc="sum",
        fill_value=0
    )
)

hour_category = hour_category.reindex(
    columns=range(24),
    fill_value=0
)

print("=" * 70)
print("FEATURE 6 - TIME-OF-DAY SPENDING MATRIX")
print("=" * 70)

display(hour_category.round(0))

======================================================================
FEATURE 6 - TIME-OF-DAY SPENDING MATRIX
======================================================================

hour,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,23
category,,,,,,,,,,,,,,,,,,,,,
Cafe,499.0,549.0,0.0,316.0,0.0,0.0,179.0,480.0,2289.0,1387.0,...,1332.0,1676.0,2704.0,3110.0,2562.0,584.0,1491.0,0.0,0.0,764.0
E-commerce,18650.0,9801.0,10246.0,14865.0,12018.0,17258.0,9249.0,10916.0,6537.0,40724.0,...,72584.0,7700.0,52046.0,35378.0,35272.0,12668.0,51190.0,35095.0,16182.0,15403.0
Entertainment,562.0,1658.0,1176.0,1650.0,1545.0,0.0,0.0,1196.0,1463.0,0.0,...,1473.0,0.0,835.0,0.0,1270.0,1852.0,952.0,0.0,343.0,0.0
Food Delivery,832.0,3017.0,928.0,1702.0,2618.0,3488.0,238.0,1498.0,3737.0,5299.0,...,4236.0,7891.0,5008.0,3951.0,13587.0,17300.0,18372.0,12123.0,9283.0,4662.0
Fuel,2675.0,2048.0,0.0,676.0,2010.0,2105.0,0.0,0.0,1727.0,2283.0,...,7828.0,11937.0,9343.0,0.0,1950.0,8351.0,705.0,11845.0,0.0,1641.0
Groceries,3895.0,1536.0,1717.0,7080.0,1169.0,0.0,1620.0,0.0,2430.0,2704.0,...,0.0,0.0,0.0,0.0,0.0,1248.0,2566.0,1891.0,0.0,2536.0
Investments,4883.0,15000.0,0.0,0.0,18834.0,4496.0,37717.0,0.0,0.0,4737.0,...,0.0,0.0,0.0,0.0,15000.0,4476.0,15000.0,0.0,15000.0,18628.0
Quick Commerce,1542.0,1402.0,1778.0,1165.0,768.0,1448.0,4432.0,252.0,1625.0,8538.0,...,3429.0,3438.0,4220.0,948.0,5965.0,6992.0,6858.0,8048.0,3061.0,1669.0
Restaurants,1411.0,960.0,1336.0,0.0,0.0,2126.0,859.0,0.0,8037.0,702.0,...,385.0,769.0,10337.0,2857.0,10151.0,8615.0,25171.0,6348.0,2782.0,0.0
Subscriptions,0.0,0.0,119.0,669.0,1998.0,745.0,657.0,272.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,119.0,0.0,0.0
Transport,646.0,260.0,358.0,337.0,577.0,2005.0,555.0,3924.0,4311.0,2695.0,...,2096.0,3608.0,3325.0,3751.0,3314.0,3543.0,4527.0,1542.0,1852.0,1458.0
Utilities,1941.0,2651.0,2625.0,0.0,1222.0,0.0,0.0,1400.0,4654.0,3004.0,...,22273.0,2060.0,602.0,2443.0,5468.0,708.0,4162.0,1472.0,2695.0,386.0

ASCII Time-of-Day Heatmap

In [22]:
print("=" * 70)
print("TIME-OF-DAY HEATMAP")
print("=" * 70)

print("Hour:", end=" ")

for hour in range(24):
    print(f"{hour:02d}", end=" ")

print()

for category in hour_category.index:

    values = hour_category.loc[category]

    max_value = values.max()

    print(f"{category:<20}", end="")

    for value in values:

        if max_value == 0:
            level = 0
        else:
            level = int(
                (value / max_value) * 5
            )

        symbols = {
            0: ".",
            1: "░",
            2: "▒",
            3: "▓",
            4: "█",
            5: "█"
        }

        print(symbols[level], end="  ")

    print()

======================================================================
TIME-OF-DAY HEATMAP
======================================================================
Hour: 00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23
Cafe                .  .  .  .  .  .  .  .  ▒  ░  █  ▒  ░  ░  ░  ▒  ▓  █  ▓  .  ░  .  .  .
E-commerce          ░  .  .  ░  .  ░  .  .  .  ▒  ░  ▓  ░  ░  █  .  ▓  ▒  ▒  .  ▓  ▒  ░  ░
Entertainment       ░  █  ▓  █  █  .  .  ▓  ▓  .  .  ▒  .  .  ▓  .  ▒  .  ▓  █  ▒  .  .  .
Food Delivery       .  .  .  .  .  .  .  .  ░  ░  .  ▒  ▓  ░  ░  ▒  ░  ░  ▓  █  █  ▓  ▒  ░
Fuel                ░  .  .  .  .  .  .  .  .  .  .  ░  █  ▓  ▓  █  ▓  .  .  ▓  .  █  .  .
Groceries           ▒  ░  ░  █  .  .  ░  .  ░  ░  ░  ▒  .  .  .  .  .  .  .  .  ░  ░  .  ░
Investments         .  .  .  .  ░  .  ▒  .  .  .  █  .  .  .  .  .  .  .  .  .  .  .  .  ░
Quick Commerce      .  .  ░  .  .  .  ▒  .  .  █  ▒  ░  ▒  ░  ▒  ▒  ▒  .  ▓  █  █  █  ░  .
Restaurants         .  .  .  .  .  .  .  .  ░  .  .  .  .  ░  .  .  ▒  .  ▒  ░  █  ░  .  .
Subscriptions       .  .  .  ░  █  ░  ░  .  .  .  .  .  .  ░  .  .  .  .  .  .  .  .  .  .
Transport           .  .  .  .  .  ▒  .  █  █  ▒  █  ▒  ▒  ▓  ▒  ▓  ▓  █  ▓  ▓  █  ░  ▒  ░
Utilities           .  .  .  .  .  .  .  .  .  .  .  ▓  .  █  ▒  .  .  .  .  .  .  .  .  .

Food Delivery Late-Night Analysis

In [23]:
food_delivery = debits[
    debits["category"] == "Food Delivery"
].copy()

late_night_food = food_delivery[
    (food_delivery["hour"] >= 21) |
    (food_delivery["hour"] <= 2)
]

if len(food_delivery) > 0:

    late_night_percentage = (
        len(late_night_food)
        / len(food_delivery)
    ) * 100

else:
    late_night_percentage = 0

print("=" * 70)
print("LATE-NIGHT FOOD DELIVERY")
print("=" * 70)

print("Total Food Delivery transactions :", len(food_delivery))
print("Late-night transactions          :", len(late_night_food))
print(f"Late-night percentage             : {late_night_percentage:.2f}%")

======================================================================
LATE-NIGHT FOOD DELIVERY
======================================================================
Total Food Delivery transactions : 344
Late-night transactions          : 73
Late-night percentage             : 21.22%

Cafe Morning Analysis

In [24]:
cafe = debits[
    debits["category"] == "Cafe"
].copy()

morning_cafe = cafe[
    (cafe["hour"] >= 8) &
    (cafe["hour"] <= 11)
]

if len(cafe) > 0:

    morning_cafe_percentage = (
        len(morning_cafe)
        / len(cafe)
    ) * 100

else:
    morning_cafe_percentage = 0

print("=" * 70)
print("CAFE MORNING PATTERN")
print("=" * 70)

print("Total Cafe transactions :", len(cafe))
print("Morning transactions    :", len(morning_cafe))
print(f"Morning percentage      : {morning_cafe_percentage:.2f}%")

======================================================================
CAFE MORNING PATTERN
======================================================================
Total Cafe transactions : 90
Morning transactions    : 31
Morning percentage      : 34.44%

FEATURE 7: Z-Score Anomaly Detection

In [25]:
# AI-assisted: Implemented the category-wise z-score formula specified
# in the Unlox Academy project brief.

analysis_debits = debits[
    debits["category"].isin(consumption_categories)
].copy()

category_mean = (
    analysis_debits
    .groupby("category")["amount"]
    .transform("mean")
)

category_std = (
    analysis_debits
    .groupby("category")["amount"]
    .transform("std")
)

analysis_debits["z_score"] = (
    analysis_debits["amount"] - category_mean
) / category_std

anomalies = analysis_debits[
    analysis_debits["z_score"] > 2
].copy()

anomalies = anomalies.sort_values(
    "z_score",
    ascending=False
)

print("=" * 70)
print("FEATURE 7 - ANOMALY DETECTION")
print("=" * 70)

print("Anomalous transactions:", len(anomalies))

======================================================================
FEATURE 7 - ANOMALY DETECTION
======================================================================
Anomalous transactions: 38

Top 10 Anomalies

In [27]:
print("=" * 70)
print("TOP ANOMALIES")
print("=" * 70)

for _, row in anomalies.head(10).iterrows():

    # Handle missing date
    if pd.isna(row['date']):
        date_str = "Unknown Date"
    else:
        date_str = row['date'].strftime('%d %b %Y')

    print(
        f"{date_str:<15} | "
        f"{str(row['vendor_clean']):<22} | "
        f"{str(row['category']):<18} | "
        f"₹{row['amount']:>10,.2f}"
    )

======================================================================
TOP ANOMALIES
======================================================================
Unknown Date    | BigBasket              | Quick Commerce     | ₹  1,865.00
Unknown Date    | BigBasket              | Quick Commerce     | ₹  1,797.00
Unknown Date    | Amazon                 | E-commerce         | ₹ 22,008.00
Unknown Date    | Amazon                 | E-commerce         | ₹ 21,986.00
Unknown Date    | Bangalore Restaurant   | Restaurants        | ₹  8,383.00
Unknown Date    | Meghana Foods          | Restaurants        | ₹  7,931.00
Unknown Date    | Amazon                 | E-commerce         | ₹ 19,917.00
Unknown Date    | Truffles               | Restaurants        | ₹  7,441.00
Unknown Date    | Bangalore Restaurant   | Restaurants        | ₹  7,314.00
Unknown Date    | BigBasket              | Quick Commerce     | ₹  1,518.00

FEATURE 8: Archetype Functions

In [28]:
# AI-assisted: Archetype functions follow the quantitative rules
# defined in the Unlox Academy project brief.

debit_total = debits["amount"].sum()


def percentage_of_debits(category):

    amount = debits[
        debits["category"] == category
    ]["amount"].sum()

    if debit_total == 0:
        return 0

    return (amount / debit_total) * 100


def detect_foodie():

    food_categories = [
        "Food Delivery",
        "Restaurants",
        "Cafe"
    ]

    amount = debits[
        debits["category"].isin(food_categories)
    ]["amount"].sum()

    percentage = (
        amount / debit_total
    ) * 100

    return percentage > 25, percentage


def detect_quick_commerce():

    percentage = percentage_of_debits(
        "Quick Commerce"
    )

    return percentage > 15, percentage


def detect_shopaholic():

    percentage = percentage_of_debits(
        "E-commerce"
    )

    return percentage > 15, percentage


def detect_investor():

    percentage = percentage_of_debits(
        "Investments"
    )

    return percentage > 15, percentage


def detect_late_night_snacker():

    food = debits[
        debits["category"] == "Food Delivery"
    ]

    if len(food) == 0:
        return False, 0

    late_night = food[
        (food["hour"] >= 21) |
        (food["hour"] <= 2)
    ]

    percentage = (
        len(late_night) / len(food)
    ) * 100

    return percentage > 50, percentage


def detect_cab_commuter():

    percentage = percentage_of_debits(
        "Transport"
    )

    return percentage > 10, percentage


def detect_subscription_lover():

    subscription_vendors = debits[
        debits["category"] == "Subscriptions"
    ]["vendor_clean"].nunique()

    return subscription_vendors >= 5, subscription_vendors


def detect_yolo_spender():

    return savings_rate < 10, savings_rate


def detect_disciplined_saver():

    return savings_rate > 40, savings_rate

Run All Archetypes

In [29]:
print("=" * 70)
print("RAHUL'S SPENDING ARCHETYPES")
print("=" * 70)

archetypes = []

foodie_flag, foodie_value = detect_foodie()

if foodie_flag:
    archetypes.append(
        ("THE FOODIE", foodie_value, "% on Food + Restaurant + Cafe")
    )

quick_flag, quick_value = detect_quick_commerce()

if quick_flag:
    archetypes.append(
        ("THE QUICK COMMERCE JUNKIE", quick_value, "% on Quick Commerce")
    )

shop_flag, shop_value = detect_shopaholic()

if shop_flag:
    archetypes.append(
        ("THE SHOPAHOLIC", shop_value, "% on E-commerce")
    )

investor_flag, investor_value = detect_investor()

if investor_flag:
    archetypes.append(
        ("THE INVESTOR", investor_value, "% on Investments")
    )

late_flag, late_value = detect_late_night_snacker()

if late_flag:
    archetypes.append(
        ("THE LATE-NIGHT SNACKER", late_value, "% Food Delivery after 9 PM")
    )

cab_flag, cab_value = detect_cab_commuter()

if cab_flag:
    archetypes.append(
        ("THE CAB COMMUTER", cab_value, "% on Transport")
    )

subscription_flag, subscription_value = detect_subscription_lover()

if subscription_flag:
    archetypes.append(
        (
            "THE SUBSCRIPTION LOVER",
            subscription_value,
            "active subscription vendors"
        )
    )

yolo_flag, yolo_value = detect_yolo_spender()

if yolo_flag:
    archetypes.append(
        (
            "THE YOLO SPENDER",
            yolo_value,
            "savings rate"
        )
    )

saver_flag, saver_value = detect_disciplined_saver()

if saver_flag:
    archetypes.append(
        (
            "THE DISCIPLINED SAVER",
            saver_value,
            "savings rate"
        )
    )


for name, value, metric in archetypes:

    if "subscription" in metric.lower():
        print(
            f"-> {name:<30} "
            f"({value:.0f} {metric})"
        )

    else:
        print(
            f"-> {name:<30} "
            f"({value:.2f} {metric})"
        )

print("\nTotal archetypes detected:", len(archetypes))

======================================================================
RAHUL'S SPENDING ARCHETYPES
======================================================================
-> THE SHOPAHOLIC                 (35.97 % on E-commerce)
-> THE YOLO SPENDER               (-229.34 savings rate)

Total archetypes detected: 2

BONUS: Bengaluru Archetype

In [30]:
def detect_pavement_coffee_connoisseur():

    cafe_vendors = debits[
        debits["category"] == "Cafe"
    ]["vendor_clean"].nunique()

    return cafe_vendors >= 4, cafe_vendors


coffee_flag, coffee_vendors = (
    detect_pavement_coffee_connoisseur()
)

print("=" * 70)
print("BONUS ARCHETYPE")
print("=" * 70)

if coffee_flag:

    print(
        "-> THE PAVEMENT COFFEE CONNOISSEUR"
    )

    print(
        f"Supporting metric: {coffee_vendors} "
        "different cafe vendors"
    )

else:

    print(
        "THE PAVEMENT COFFEE CONNOISSEUR was not detected."
    )

======================================================================
BONUS ARCHETYPE
======================================================================
THE PAVEMENT COFFEE CONNOISSEUR was not detected.

BONUS: Day-of-Week Analysis

In [31]:
print("=" * 70)
print("BONUS - DAY-OF-WEEK ANALYSIS")
print("=" * 70)

weekday_order = [
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
    "Sunday"
]

day_spending = (
    debits
    .groupby("day_of_week")["amount"]
    .sum()
    .reindex(weekday_order)
    .fillna(0)
)

for day, amount in day_spending.items():

    print(
        f"{day:<12} ₹{amount:>12,.2f}"
    )

weekend_spend = day_spending[
    ["Saturday", "Sunday"]
].sum()

weekday_spend = day_spending[
    [
        "Monday",
        "Tuesday",
        "Wednesday",
        "Thursday",
        "Friday"
    ]
].sum()

print("\nWeekend spend :", f"₹{weekend_spend:,.2f}")
print("Weekday spend :", f"₹{weekday_spend:,.2f}")

if weekday_spend > 0:

    weekend_difference = (
        (weekend_spend - weekday_spend)
        / weekday_spend
    ) * 100

    print(
        f"Weekend vs weekday difference: "
        f"{weekend_difference:.2f}%"
    )

======================================================================
BONUS - DAY-OF-WEEK ANALYSIS
======================================================================
Monday       ₹   17,106.00
Tuesday      ₹   35,776.00
Wednesday    ₹   29,859.00
Thursday     ₹   11,988.00
Friday       ₹   43,159.00
Saturday     ₹    5,260.00
Sunday       ₹   62,162.00

Weekend spend : ₹67,422.00
Weekday spend : ₹137,888.00
Weekend vs weekday difference: -51.10%

BONUS: 3-Month Spend Forecast

In [32]:
print("=" * 70)
print("BONUS - NEXT MONTH SPEND FORECAST")
print("=" * 70)

monthly_total = (
    debits
    .groupby("month")["amount"]
    .sum()
    .reindex(range(1, 7))
    .fillna(0)
)

for month, amount in monthly_total.items():

    print(
        f"{month_names[month]} : ₹{amount:,.2f}"
    )

last_three_months = monthly_total.iloc[-3:].values

forecast = np.mean(last_three_months)

print(
    f"\nForecast for July 2024 "
    f"(3-month average): ₹{forecast:,.2f}"
)

======================================================================
BONUS - NEXT MONTH SPEND FORECAST
======================================================================
Jan : ₹14,972.00
Feb : ₹6,390.00
Mar : ₹26,578.00
Apr : ₹5,246.00
May : ₹21,011.00
Jun : ₹9,292.00

Forecast for July 2024 (3-month average): ₹11,849.67

Monthly Spending Summary

In [33]:
print("=" * 70)
print("MONTHLY SPENDING")
print("=" * 70)

for month_number in range(1, 7):

    amount = monthly_total.loc[month_number]

    percentage = (
        amount / total_debits
    ) * 100

    bar = "#" * int(percentage)

    print(
        f"{month_names[month_number]} "
        f"₹{amount:>12,.2f} "
        f"{bar}"
    )

======================================================================
MONTHLY SPENDING
======================================================================
Jan ₹   14,972.00
Feb ₹    6,390.00
Mar ₹   26,578.00 #
Apr ₹    5,246.00
May ₹   21,011.00 #
Jun ₹    9,292.00

Final SpendDNA Report

In [35]:
# ============================================================
# FINAL SPENDDNA REPORT
# ============================================================

print("\n" + "=" * 75)
print("                    SPENDDNA FINAL REPORT")
print("                 Your Wallet's Financial DNA")
print("=" * 75)

# ------------------------------------------------------------
# 1. EXECUTIVE FINANCIAL SUMMARY
# ------------------------------------------------------------

print("\n" + "-" * 75)
print("1. EXECUTIVE FINANCIAL SUMMARY")
print("-" * 75)

print(f"Total Transactions : {transaction_count:,}")
print(f"Unique Vendors     : {unique_vendors:,}")
print(f"Total Credits      : ₹{total_credits:,.2f}")
print(f"Total Debits       : ₹{total_debits:,.2f}")
print(f"Net Change         : ₹{net_change:,.2f}")
print(f"Savings Rate       : {savings_rate:.2f}%")

# ------------------------------------------------------------
# 2. CATEGORY-WISE SPENDING
# ------------------------------------------------------------

print("\n" + "-" * 75)
print("2. CATEGORY-WISE SPENDING")
print("-" * 75)

if len(category_spend) > 0:

    total_category_spend = category_spend.sum()

    for category, amount in category_spend.sort_values(
        ascending=False
    ).items():

        percentage = (
            amount / total_category_spend * 100
            if total_category_spend > 0 else 0
        )

        bar = "█" * max(1, int(percentage / 2))

        print(
            f"{str(category):<22} "
            f"₹{amount:>12,.2f}  "
            f"{percentage:>6.2f}%  "
            f"{bar}"
        )

# ------------------------------------------------------------
# 3. TOP VENDORS
# ------------------------------------------------------------

print("\n" + "-" * 75)
print("3. TOP VENDORS BY SPENDING")
print("-" * 75)

if len(vendor_spend) > 0:

    for i, (vendor, amount) in enumerate(
        vendor_spend.sort_values(
            ascending=False
        ).head(10).items(),
        start=1
    ):
        print(
            f"{i:>2}. "
            f"{str(vendor):<25} "
            f"₹{amount:>12,.2f}"
        )

# ------------------------------------------------------------
# 4. MONTHLY SPENDING TRENDS
# ------------------------------------------------------------

print("\n" + "-" * 75)
print("4. MONTHLY SPENDING TRENDS")
print("-" * 75)

if len(monthly_total) > 0:

    max_month_value = monthly_total.max()

    for month, amount in monthly_total.items():

        bar_length = (
            int((amount / max_month_value) * 35)
            if max_month_value > 0 else 0
        )

        print(
            f"{str(month):<12} "
            f"₹{amount:>12,.2f}  "
            f"{'█' * bar_length}"
        )

# ------------------------------------------------------------
# 5. TIME-OF-DAY PATTERNS
# ------------------------------------------------------------

print("\n" + "-" * 75)
print("5. TIME-OF-DAY SPENDING PATTERNS")
print("-" * 75)

print(
    f"Late-night food delivery : "
    f"{late_night_percentage:.2f}%"
)

print(
    f"Morning cafe spending    : "
    f"{morning_cafe_percentage:.2f}%"
)

if late_night_percentage > 20:
    print("Insight: Significant late-night food spending detected.")
else:
    print("Insight: Late-night food spending is relatively controlled.")

if morning_cafe_percentage > 15:
    print("Insight: Noticeable morning cafe spending detected.")
else:
    print("Insight: Morning cafe spending is relatively controlled.")

# ------------------------------------------------------------
# 6. ANOMALIES
# ------------------------------------------------------------

print("\n" + "-" * 75)
print("6. TOP ANOMALIES")
print("-" * 75)

if len(anomalies) == 0:

    print("No significant anomalies detected.")

else:

    for _, row in anomalies.head(10).iterrows():

        # Prevent NaT strftime error
        if pd.isna(row['date']):
            date_str = "Unknown"
        else:
            date_str = row['date'].strftime('%d %b %Y')

        vendor = str(row.get('vendor_clean', 'Unknown'))
        category = str(row.get('category', 'Unknown'))
        amount = row.get('amount', 0)

        print(
            f"{date_str:<15} | "
            f"{vendor:<22} | "
            f"{category:<18} | "
            f"₹{amount:>10,.2f}"
        )

# ------------------------------------------------------------
# 7. SPENDING ARCHETYPE
# ------------------------------------------------------------

print("\n" + "-" * 75)
print("7. SPENDING ARCHETYPE")
print("-" * 75)

if isinstance(archetypes, (list, tuple)):

    for archetype in archetypes:
        print(f"• {archetype}")

else:

    print(archetypes)

# ------------------------------------------------------------
# 8. KEY INSIGHTS
# ------------------------------------------------------------

print("\n" + "-" * 75)
print("8. KEY INSIGHTS")
print("-" * 75)

# Highest spending category
if len(category_spend) > 0:

    top_category = category_spend.idxmax()
    top_category_amount = category_spend.max()

    print(
        f"• Highest spending category: "
        f"{top_category} "
        f"(₹{top_category_amount:,.2f})"
    )

# Highest spending vendor
if len(vendor_spend) > 0:

    top_vendor = vendor_spend.idxmax()
    top_vendor_amount = vendor_spend.max()

    print(
        f"• Highest spending vendor: "
        f"{top_vendor} "
        f"(₹{top_vendor_amount:,.2f})"
    )

# Savings insight
if savings_rate >= 20:

    print(
        f"• Savings performance is strong at "
        f"{savings_rate:.2f}%."
    )

elif savings_rate >= 10:

    print(
        f"• Savings performance is moderate at "
        f"{savings_rate:.2f}%."
    )

else:

    print(
        f"• Savings rate is relatively low at "
        f"{savings_rate:.2f}%; spending can be reviewed."
    )

# Anomaly insight
print(
    f"• {len(anomalies)} potentially unusual "
    f"transaction(s) were identified."
)

# ------------------------------------------------------------
# 9. FINAL SUMMARY
# ------------------------------------------------------------

print("\n" + "=" * 75)
print("                    FINAL SPENDDNA SUMMARY")
print("=" * 75)

print(
    f"""
SpendDNA analyzed {transaction_count:,} transactions
across {unique_vendors:,} unique vendors.

Total money received : ₹{total_credits:,.2f}
Total money spent    : ₹{total_debits:,.2f}
Net financial change : ₹{net_change:,.2f}
Savings rate         : {savings_rate:.2f}%

The analysis identified the major spending categories,
frequent vendors, monthly spending patterns, time-of-day
behaviour and potentially unusual transactions.

These insights can help the user understand spending habits,
identify unusual expenses and make better financial decisions.
"""
)

print("=" * 75)
print("                    END OF REPORT")
print("=" * 75)

===========================================================================
                    SPENDDNA FINAL REPORT
                 Your Wallet's Financial DNA
===========================================================================

---------------------------------------------------------------------------
1. EXECUTIVE FINANCIAL SUMMARY
---------------------------------------------------------------------------
Total Transactions : 1,310
Unique Vendors     : 41
Total Credits      : ₹509,774.00
Total Debits       : ₹1,678,901.00
Net Change         : ₹-1,169,127.00
Savings Rate       : -229.34%

---------------------------------------------------------------------------
2. CATEGORY-WISE SPENDING
---------------------------------------------------------------------------
E-commerce             ₹  603,877.00   38.45%  ███████████████████
Investments            ₹  248,160.00   15.80%  ███████
Utilities              ₹  154,674.00    9.85%  ████
Food Delivery          ₹  150,839.00    9.61%  ████
Restaurants            ₹   97,912.00    6.23%  ███
Fuel                   ₹   89,303.00    5.69%  ██
Quick Commerce         ₹   81,725.00    5.20%  ██
Transport              ₹   55,884.00    3.56%  █
Groceries              ₹   37,463.00    2.39%  █
Cafe                   ₹   28,155.00    1.79%  █
Entertainment          ₹   16,888.00    1.08%  █
Subscriptions          ₹    5,504.00    0.35%  █

---------------------------------------------------------------------------
3. TOP VENDORS BY SPENDING
---------------------------------------------------------------------------
 1. Amazon                    ₹  328,530.00
 2. Zerodha                   ₹  210,000.00
 3. Flipkart                  ₹  177,510.00
 4. Rent                      ₹  108,000.00
 5. Swiggy                    ₹   95,523.00
 6. Myntra                    ₹   69,529.00
 7. Indian Oil                ₹   56,335.00
 8. Zomato                    ₹   55,316.00
 9. Cash Withdrawal           ₹   45,500.00
10. Bangalore Restaurant      ₹   44,978.00

---------------------------------------------------------------------------
4. MONTHLY SPENDING TRENDS
---------------------------------------------------------------------------
1            ₹   14,972.00  ███████████████████
2            ₹    6,390.00  ████████
3            ₹   26,578.00  ███████████████████████████████████
4            ₹    5,246.00  ██████
5            ₹   21,011.00  ███████████████████████████
6            ₹    9,292.00  ████████████

---------------------------------------------------------------------------
5. TIME-OF-DAY SPENDING PATTERNS
---------------------------------------------------------------------------
Late-night food delivery : 21.22%
Morning cafe spending    : 34.44%
Insight: Significant late-night food spending detected.
Insight: Noticeable morning cafe spending detected.

---------------------------------------------------------------------------
6. TOP ANOMALIES
---------------------------------------------------------------------------
Unknown         | BigBasket              | Quick Commerce     | ₹  1,865.00
Unknown         | BigBasket              | Quick Commerce     | ₹  1,797.00
Unknown         | Amazon                 | E-commerce         | ₹ 22,008.00
Unknown         | Amazon                 | E-commerce         | ₹ 21,986.00
Unknown         | Bangalore Restaurant   | Restaurants        | ₹  8,383.00
Unknown         | Meghana Foods          | Restaurants        | ₹  7,931.00
Unknown         | Amazon                 | E-commerce         | ₹ 19,917.00
Unknown         | Truffles               | Restaurants        | ₹  7,441.00
Unknown         | Bangalore Restaurant   | Restaurants        | ₹  7,314.00
Unknown         | BigBasket              | Quick Commerce     | ₹  1,518.00

---------------------------------------------------------------------------
7. SPENDING ARCHETYPE
---------------------------------------------------------------------------
• ('THE SHOPAHOLIC', np.float64(35.968588975764504), '% on E-commerce')
• ('THE YOLO SPENDER', np.float64(-229.34221831635196), 'savings rate')

---------------------------------------------------------------------------
8. KEY INSIGHTS
---------------------------------------------------------------------------
• Highest spending category: E-commerce (₹603,877.00)
• Highest spending vendor: Amazon (₹328,530.00)
• Savings rate is relatively low at -229.34%; spending can be reviewed.
• 38 potentially unusual transaction(s) were identified.

===========================================================================
                    FINAL SPENDDNA SUMMARY
===========================================================================

SpendDNA analyzed 1,310 transactions
across 41 unique vendors.

Total money received : ₹509,774.00
Total money spent    : ₹1,678,901.00
Net financial change : ₹-1,169,127.00
Savings rate         : -229.34%

The analysis identified the major spending categories,
frequent vendors, monthly spending patterns, time-of-day
behaviour and potentially unusual transactions.

These insights can help the user understand spending habits,
identify unusual expenses and make better financial decisions.

===========================================================================
                    END OF REPORT
===========================================================================

Three Data-Specific Insights

In [36]:
print("=" * 72)
print("KEY INSIGHTS")
print("=" * 72)

# Insight 1
top_category = category_spend.idxmax()
top_category_amount = category_spend.max()

top_category_percentage = (
    top_category_amount /
    category_spend.sum()
) * 100

print(
    f"1. {top_category} is the largest consumption category, "
    f"accounting for {top_category_percentage:.2f}% "
    f"of analysed debit spending."
)

# Insight 2
print(
    f"2. {late_night_percentage:.2f}% of Food Delivery "
    f"transactions occur during the late-night window "
    f"of 21:00-02:00."
)

# Insight 3
top_vendor = vendor_spend.idxmax()
top_vendor_amount = vendor_spend.max()

print(
    f"3. {top_vendor} is the highest-spend vendor with "
    f"₹{top_vendor_amount:,.2f} in total debit transactions."
)

========================================================================
KEY INSIGHTS
========================================================================
1. E-commerce is the largest consumption category, accounting for 38.45% of analysed debit spending.
2. 21.22% of Food Delivery transactions occur during the late-night window of 21:00-02:00.
3. Amazon is the highest-spend vendor with ₹328,530.00 in total debit transactions.

Data Quality Summary

In [37]:
print("=" * 72)
print("DATA QUALITY SUMMARY")
print("=" * 72)

print(f"Original rows          : {len(df)}")
print(f"Duplicates removed     : {duplicates_before}")
print(f"Clean rows             : {len(df_clean)}")
print(f"Invalid dates          : {invalid_dates}")
print(f"Invalid amounts        : {invalid_amounts}")
print(f"Uncategorised vendors  : {len(uncategorised)}")

print("\nCategory coverage:")
print(
    df_clean["category"]
    .value_counts()
)

========================================================================
DATA QUALITY SUMMARY
========================================================================
Original rows          : 1328
Duplicates removed     : 18
Clean rows             : 1310
Invalid dates          : 1167
Invalid amounts        : 0
Uncategorised vendors  : 59

Category coverage:
category
Food Delivery        344
Transport            236
E-commerce           172
Quick Commerce       144
Cafe                  90
Restaurants           63
Uncategorised         59
Utilities             53
Fuel                  28
Investments           23
Groceries             22
Entertainment         21
Subscriptions         18
Cash Withdrawal       17
Personal Transfer     14
Income                 6
Name: count, dtype: int64

Final Verification

In [38]:
print("=" * 72)
print("FINAL PROJECT VERIFICATION")
print("=" * 72)

checks = {
    "Dataset loaded": len(df) > 0,
    "Duplicates removed": duplicates_before >= 0,
    "Dates parsed": invalid_dates == 0,
    "Amounts parsed": invalid_amounts == 0,
    "Vendor column created": "vendor_clean" in df_clean.columns,
    "Category column created": "category" in df_clean.columns,
    "Month analysis completed": len(monthly_category) > 0,
    "Hour analysis completed": "hour" in df_clean.columns,
    "Anomaly detection completed": "z_score" in analysis_debits.columns,
    "Archetypes detected": len(archetypes) > 0
}

for check, result in checks.items():

    status = "PASS" if result else "CHECK"

    print(
        f"{check:<35} : {status}"
    )

print()
print("SpendDNA project analysis completed.")

========================================================================
FINAL PROJECT VERIFICATION
========================================================================
Dataset loaded                      : PASS
Duplicates removed                  : PASS
Dates parsed                        : CHECK
Amounts parsed                      : PASS
Vendor column created               : PASS
Category column created             : PASS
Month analysis completed            : PASS
Hour analysis completed             : PASS
Anomaly detection completed         : PASS
Archetypes detected                 : PASS

SpendDNA project analysis completed.

Reflection

In [39]:
print("=" * 72)
print("REFLECTION")
print("=" * 72)

print("""
Through this project, I learned how raw financial transaction data
can be transformed into meaningful business insights.

The main challenges were handling multiple date formats, cleaning
different currency formats, normalising merchant descriptions and
categorising transactions.

I also learned how category-wise z-score analysis can be used to
identify unusual transactions and how rule-based logic can be used
to identify spending archetypes.

The project helped me understand how transaction analytics can be
used in real fintech applications.
""")

========================================================================
REFLECTION
========================================================================

Through this project, I learned how raw financial transaction data
can be transformed into meaningful business insights.

The main challenges were handling multiple date formats, cleaning
different currency formats, normalising merchant descriptions and
categorising transactions.

I also learned how category-wise z-score analysis can be used to
identify unusual transactions and how rule-based logic can be used
to identify spending archetypes.

The project helped me understand how transaction analytics can be
used in real fintech applications.

AI Assistance Disclosure

In [40]:
print("=" * 72)
print("AI-ASSISTANCE DISCLOSURE")
print("=" * 72)

print("""
AI assistance was used for:
- Understanding Pandas and NumPy syntax.
- Debugging code structure.
- Improving code readability.
- Understanding the project requirements.

The transaction data was analysed programmatically from the
provided rahul_transactions.csv dataset.

Vendor mappings, calculations and final insights were generated
from the supplied dataset.
""")

========================================================================
AI-ASSISTANCE DISCLOSURE
========================================================================

AI assistance was used for:
- Understanding Pandas and NumPy syntax.
- Debugging code structure.
- Improving code readability.
- Understanding the project requirements.

The transaction data was analysed programmatically from the
provided rahul_transactions.csv dataset.

Vendor mappings, calculations and final insights were generated
from the supplied dataset.